version: 0.2

env:
  variables:
    S3_BUCKET_NAME: <your-bucket-name>

phases:
  pre_build:
    commands:
      - yarn install
      - rm -f .env*
      - cp .env.production .env
      - yarn run build
  build:
    commands:
      - aws s3 sync build/ s3://$S3_BUCKET_NAME/
      - aws cloudfront create-invalidation --distribution-id "E3K2LH4M35U8R" --paths '/*'
